FROM node:20-alpine3.17

WORKDIR /server/

COPY package*.json /server/

RUN npm install

COPY . /server/

EXPOSE 80

COPY ./startup.sh /server/

RUN chmod +x /server/startup.sh

ENTRYPOINT [ "sh", "/server/startup.sh" ]
